### ISSUE TITLE
pieces aren't getting created with game

### ISSUE THREAD

**Issue by ghost** [PushThePiece/chess#77]
Game is created has 32 pieces
     Failure/Error: expect(@game.pieces.count).to eq(32)
     
       expected: 32
            got: 0
     
       (compared using ==)

**Comment by rwang430** [comment]
tested to see where the error is coming from.

@game is coming back as nil
so when @game = Game.create it's nil in all fields
#<Game id: nil, white_user_id: nil, black_user_id: nil, turn: nil>

**Comment by ghost** [comment]
I'm guessing this broke it in the game class:
```
  belongs_to :black_player, class_name: "User", foreign_key: :black_user_id, optional: :true
  belongs_to :white_player, class_name: "User", foreign_key: :white_user_id
```
I'm not sure what those lines are supposed to do. If you look at the example from the docs (http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association):
```
class Book < ApplicationRecord  
         belongs_to :author
end
```
it goes on the class name, not specific fields like white_player etc.

**Comment by gretchonian** [comment]
Fixed
