### ISSUE TITLE
flash message says it's not my turn when it is

### ISSUE THREAD

**Issue by ghost** [PushThePiece/chess#80]
![chess](https://user-images.githubusercontent.com/21265184/30190984-0cae9e18-940c-11e7-8823-c3ea4435b17e.jpeg)

It says it's white's turn, but when I move a white piece, I get the red flash message saying it's not my turn.

**Comment by ghost** [comment]
Moving any piece gets rejected for that reason

**Comment by gretchonian** [comment]
This working on my db. Try a new game with new different players.

**Comment by ghost** [comment]
Yes it's working.
